name: Deploy para VPS com Imagem Docker

on:
  push:
    branches: [main]

jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
      - name: Login no GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_push
    env:
      CONTAINER_NAME: matematicando-web
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Remove o container existente se ele existir
            if docker ps -a | grep "${{ env.CONTAINER_NAME }}" > /dev/null; then
              docker stop ${{ env.CONTAINER_NAME }} || true
              docker rm ${{ env.CONTAINER_NAME }} || true
            fi

            # Stop any existing containers using the image
            containers=$(docker ps -aqf "ancestor=ghcr.io/${{ github.repository }}:${{ github.sha }}")
            if [ -n "$containers" ]; then
              docker stop $containers || true
              docker rm $containers || true
            fi

            # Pull the latest image
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository }}:${{ github.sha }} || exit 1

            # Run the container, passing secrets directly via -e and mounting the config directory
            docker run -d --restart=unless-stopped -p 4000:4000 --name ${{ env.CONTAINER_NAME }} \
              ghcr.io/${{ github.repository }}:${{ github.sha }}
